#!/bin/sh
# stunnel in front of the p11-kit socket — the SERVER half of the token transport.
#
# Kept as a script rather than an inline `command:` for the same reason token.sh is: a
# manifest that carries shell is a manifest nobody can run by hand to see what it does, and
# apply.sh already ships this directory as the fastpki-bootstrap ConfigMap.
set -eu
D=/var/pki/tls/p11
# ⚠️ THE PRIVATE KEY IS A TOKEN OBJECT, so there is no server.key to look for. certgen mints
# `p11-server` in this node's own token; a key file here would be the one private key in the
# deployment living outside a token.
if [ ! -f "$D/server.crt" ]; then
  echo "p11-tls: FATAL - $D/server.crt is missing." >&2
  echo "p11-tls:   The transport material is generated by certgen under P11_TLS=on." >&2
  # ⚠️ NAME THE WORKLOAD THAT RUNS certgen. It is this pod's own init container, and there is no
  # certgen Job to re-run; the Compose copy of this message prints a runnable command, and so
  # does this one.
  echo "p11-tls:   certgen runs in this pod's init container. Set P11_TLS=on in k8s/env.sh and" >&2
  echo "p11-tls:   re-run apply.sh, which restarts the pods so the init container runs again." >&2
  echo "p11-tls:   The renewal loop re-enters the same block daily with: certgen.sh --p11-only" >&2
  exit 1
fi
if [ ! -d "$D/clients" ]; then
  echo "p11-tls: FATAL - $D/clients does not exist, so no client could be trusted." >&2
  exit 1
fi
# Build the trust directory from what the mesh has replicated, rather than from files an
# operator carried across. A node publishes its own certificate into its own `datacenters`
# row; this materialises every one it finds. Best-effort: a node with no database reachable
# still starts with whatever is already on disk, which is the safe direction — refusing to
# start would take the token offline over a transient.
# ⚠️ AND PUBLISH THE OTHER HALF. A peer verifies the host it dials against a
# certificate this node has advertised; without this it would be left pinning one it
# generated itself, which this node has never presented, and no handshake could succeed.
fastpki-config --config /app/config/bootstrap.conf p11-server-publish "$D/server.crt" || \
  echo "p11-tls: WARNING - could not publish this node's server certificate; peers that have not already synced it cannot verify this host" >&2
fastpki-config --config /app/config/bootstrap.conf p11-clients-sync "$D/clients" || \
  echo "p11-tls: WARNING - could not refresh the trust directory; using what is on disk" >&2

# ⚠️ AND THE DIALLING HALF, AT START — NOT ONLY IN THE DAILY RENEWAL LOOP. Every server with
# P11_TLS on publishes its own token AND may dial a peer to replicate a CA key out of one.
# When this ran only daily, a freshly applied cluster had an empty servers/ directory and
# `fastpki-ca key replicate --from` refused with "no peer token host can be verified" for up
# to a day, with nothing to say it was a matter of waiting.
mkdir -p "$D/servers"
fastpki-config --config /app/config/bootstrap.conf p11-client-publish "$D/client.crt" || \
  echo "p11-tls: WARNING - could not publish this node's client certificate; peers cannot admit it until this succeeds" >&2
fastpki-config --config /app/config/bootstrap.conf p11-servers-sync "$D/servers" || \
  echo "p11-tls: WARNING - could not refresh $D/servers; using what is on disk" >&2
openssl rehash "$D/servers" >/dev/null 2>&1 || true

# ⚠️ verifyPeer AND verifyChain, and a CApath holding only what certgen minted. C_Login
# carries the PIN protecting every CA private key in the token, so this is the only thing
# between the network and every CA. checkHost/checkIP are absent on purpose: pod addresses
# are dynamic, so the identity is the pinned certificate, not where it answers from.
cat > /tmp/stunnel.conf <<CONF
foreground = yes
pid =

[p11]
accept = 0.0.0.0:12345
connect = /run/p11/pkcs11.sock
cert = $D/server.crt
key = pkcs11:token=${PKCS11_TOKEN:-fastpki};object=p11-server;type=private?pin-source=${PKCS11_PIN_FILE:-/var/pki/tls/pin}
CApath = $D/clients
verifyPeer = yes
verifyChain = yes
CONF

# ⚠️ stunnel CANNOT SEE THE pkcs11 PROVIDER WITHOUT A CONFIG SAYING SO. FastPKI's own
# binaries load it programmatically (ensure_pkcs11_provider, src/lib/x509.cpp); stunnel is a
# stock Alpine binary reading the stock openssl.cnf, which activates nothing. Exported just
# before the exec so it reaches stunnel and not the fastpki-config calls above.
#
# ⚠️ pkcs11-module-path IS THE CLIENT SHIM, NEVER libsofthsm2.so. Loading SoftHSM in-process
# re-enters libcrypto while it holds a lock and DEADLOCKS — a hang, not a failure.
cat > /tmp/stunnel-openssl.cnf <<CONF
openssl_conf = fastpki_conf
[fastpki_conf]
providers = fastpki_providers
[fastpki_providers]
default = fastpki_default
pkcs11  = fastpki_pkcs11
[fastpki_default]
activate = 1
[fastpki_pkcs11]
module = ${OSSL_MODULES_DIR:-/usr/lib/ossl-modules}/pkcs11.so
pkcs11-module-path = ${PKCS11_MODULE:-/usr/lib/pkcs11/p11-kit-client.so}
activate = 1
CONF
# ⚠️ A PEER THAT PUBLISHES LATER MUST BE ADMITTED WITHOUT A RESTART. Everything above runs
# once, at start, so the node that came up FIRST admits only itself and a peer publishing
# its client certificate later is refused in the TLS handshake — reported on the dialling
# side as `C_Initialize failed (rc=48)`, which names nothing about certificates. `CApath` is
# looked up per handshake by hash, so a peer's FIRST certificate is admitted by refreshing the
# directory alone. Best-effort: on failure the previous contents stay valid.
#
# ⚠️ A REPLACED CERTIFICATE IS NOT, AND NEEDS stunnel TO RELOAD. OpenSSL's hashed-directory lookup
# keeps a certificate in memory once it has loaded it, and a peer's new certificate has the same
# subject — so the same hash — as the one it replaces. Measured on a Kubernetes pair: a server
# rebuilt from empty claims minted a new transport keypair, its certificate was on disk here
# within a minute, and every handshake was still refused ("certificate not found in local
# repository") against the cached old one, so the rebuilt token could never be refilled. A
# SIGHUP makes stunnel build its TLS context again; stunnel is this container's PID 1.
( while sleep 60; do
    _before=$(cat "$D"/clients/*.crt 2>/dev/null | cksum)
    fastpki-config --config /app/config/bootstrap.conf p11-clients-sync "$D/clients" >/dev/null 2>&1 \
      && openssl rehash "$D/clients" >/dev/null 2>&1
    fastpki-config --config /app/config/bootstrap.conf p11-servers-sync "$D/servers" >/dev/null 2>&1 \
      && openssl rehash "$D/servers" >/dev/null 2>&1
    [ "$(cat "$D"/clients/*.crt 2>/dev/null | cksum)" = "$_before" ] || kill -HUP 1 2>/dev/null
  done ) &
echo "p11-tls: serving the token over mTLS on :12345 (clients pinned in $D/clients)"
# ⚠️ AS THE TOKEN'S USER, WHICH THIS CONTAINER RUNS AS. stunnel's `key =` is a pkcs11: URI, and
# the token sidecar runs `p11-kit-server -u fastpki`, which authorises by the connecting
# process's uid and serves that user alone — as root the handle cannot be opened and stunnel
# dies with "Failed to initialize TLS context", naming TLS and not a uid. Compose runs its
# container as root and drops with su; here the pod's init container has already handed
# /var/pki to fastpki, so nothing in this script needs root and the container never has it.
export OPENSSL_CONF=/tmp/stunnel-openssl.cnf
exec stunnel /tmp/stunnel.conf
